# The hologram plugin that SkJade should use, if holographic elements are enabled.
# Must be supported, only the following are currently:
# - DecentHolograms
hologram-plugin: DecentHolograms
# Whether players with the permission 'skjade.notify' or operator
# status should be notified on join if an SkJade update is due.
new-version-alerts: true

# This part of the config enables certain syntax for SkJade, so you can choose what to use.

# Whether binflop sending should be enabled.
binflop-elements-enabled: true
# Whether lasers should be enabled or not.
laser-elements-enabled: true
# Whether holograms should be enabled or not.
holographic-elements-enabled: true
# All other elements.
misc-elements-enabled: true