# Whether holograms should be enabled or not.
holograms-enabled: true
# The hologram plugin that SkJade should use.
# Must be supported, only the following are currently:
# - DecentHolograms
hologram-plugin: DecentHolograms
# Whether players with the permission 'skjade.notify' or operator
# status should be notified on join if an SkJade update is due.
new-version-alerts: true