name: SkJade
version: '${project.version}'
description: "§7Enhance §eSkript §7with this add-on and use custom syntax! §c❤"
author: Ankoki
website: 'https://www.github.com/Ankoki/SkJade'
api-version: 1.16
main: com.ankoki.skjade.SkJade
commands:
  skjade:
    aliases:
      - skj
    description: Shows the version of SkJade that is currently being run.
depend:
  - Skript
softdepend:
  - HolographicDisplays